# MOVIE DB PREPROCESSING

In [1]:
import pandas as pd

movie_db_df = pd.read_csv('data/movie_database_with_license_fee.csv', parse_dates=['release_date'])

filtered_df = movie_db_df[
    (movie_db_df['vote_average'] >= 5.5) & 
    (movie_db_df['vote_average'] <= 7.5) & 
    (movie_db_df['release_date'] > '2000-01-01') & 
    (movie_db_df['revenue'] > movie_db_df['budget']) & 
    (movie_db_df['license_fee'] < 1e6)
]

filtered_df.to_csv('data/filtered_movie_database.csv', index=False)

In [4]:
filtered_movie_db_df = pd.read_csv('data/filtered_movie_database.csv', parse_dates=['release_date'])

In [5]:
print(len(movie_db_df))
print(len(filtered_movie_db_df))

5920
2052


In [25]:
import numpy as np

# Create a small dataset
# 10 samples, 5 features (with 2 identical features and 1 constant feature)
X_train = np.array([
    [1, 2, 3, 3, 3, 7, 3],
    [4, 5, 6, 6,6, 7, 3],
    [7, 8, 9, 9,9, 7, 3],
    [10, 11, 12,12, 12, 7, 3],
    [13, 14, 15,15, 15, 7, 3],
    [16, 17, 18,18, 18, 7, 3],
    [19, 20, 21,21, 21, 7, 3],
    [22, 23, 24,24, 24, 7, 3],
    [25, 26, 27,27, 27, 7, 3],
    [28, 29, 30,30, 30, 7, 3]
])

# Identify constant features
constant_features = np.all(X_train == X_train[0, :], axis=0)
constant_feature_indices = np.where(constant_features)[0]
print("Constant feature indices (0-based):", constant_feature_indices)

# Filter out constant columns
X_train = X_train[:, ~constant_features]

# Identify duplicate features
_, unique_indices = np.unique(X_train, axis=1, return_index=True)
duplicate_feature_indices = [i for i in range(X_train.shape[1]) if i not in unique_indices]
print("Duplicate feature indices (0-based):", duplicate_feature_indices)

# Sort indices to maintain order
unique_indices = np.sort(unique_indices)

# Filter out duplicate columns
X_train = X_train[:, unique_indices]

# Final transformed datasets
print("Transformed X_train:\n", X_train)


Constant feature indices (0-based): [5 6]
Duplicate feature indices (0-based): [3, 4]
Transformed X_train:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
